### ISSUE TITLE
Issue installing

### ISSUE THREAD

**Issue by christianlarsen** [NielsLiisberg/ILEcurl#1]
Hi Niels,

I have been trying to install this utility, but im getting an error when Im using make.  
First, the error was because the "compile.py". It says that it cannot found "compile.py" (im using make from inside the ILEcurl folder, so that file exists). After that, I tried to change the makefile adding /QOpenSys/pkgs/bin/python before compile.py, but then I receive a different error.... it says that there is an error in the "print ln" (line 129). Ive been watching the code, and it seems to be okay, of course... 
I dont know if Im doing something wrong?

I have been using QSH for installing it....

**Comment by NielsLiisberg** [comment]
Hello Christian,

Thank you for your input.

I'll have to run through the build process on a blank partition. I'll be
back..

**Comment by NielsLiisberg** [comment]
OK, got it.
I have changed it to use python3.9 and you have to yum install that:
```
yum install python39
```
